## PRACTICA OBLIGATORIA: **Álgebra y NumPy**

## PARTE I:

In [9]:
import numpy as np
compradores = [
    [6,4,3,1],
    [3,6,2,2],
    [3,4,3,1]
]
matriz_vendedores = [
    [1.50,1],
    [2,2.50],
    [5,4.50],
    [16,17]
]
matriz_vendedores_np = np.array(matriz_vendedores)
compradores_np = np.array(compradores)

costes = np.dot(compradores_np,matriz_vendedores_np)
print(costes)

clientes = ["Rafita","Nachito","Clarita"]
tiendas = ["Manolo Bakes", "Starbucks"]

for i , clientes in enumerate(clientes):
    tiend_barata = tiendas[np.argmin(costes[i])]
    print(clientes, "le sale mas barato en:\n",tiend_barata)





[[48.  46.5]
 [58.5 61. ]
 [43.5 43.5]]
Rafita le sale mas barato en:
 Starbucks
Nachito le sale mas barato en:
 Manolo Bakes
Clarita le sale mas barato en:
 Manolo Bakes


## PARTE II: Clasificador de Películas

In [11]:
generos_peliculas = ["Acción","Aventura","Animación","Comedia","Romance"]

peliculas = {
    "Toy Story":[0,1,1,1,0],
    "Jumanji":[0,1,0,0,0],
    "Mortal Kombat":[1,1,0,0,0],
    "Pocahontas":[0,0,1,1,0]
}


In [22]:
matriz_peliculas = np.array(list(peliculas.values()))
print("Matriz:\n",matriz_peliculas)
print("Dimension:\n",matriz_peliculas.ndim)
print("Shape:\n",matriz_peliculas.shape)
print("Tamaño:\n",matriz_peliculas.size)
print("Tipo:\n",type(matriz_peliculas))

Matriz:
 [[0 1 1 1 0]
 [0 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 1 0]]
Dimension:
 2
Shape:
 (4, 5)
Tamaño:
 20
Tipo:
 <class 'numpy.ndarray'>


In [27]:
def similitud_coseno(vec1,vec2):
    numerador = np.dot(vec1,vec2)
    denominador = np.linalg.norm(vec1) * np.linalg.norm(vec2)
    resultado = numerador / denominador
    return resultado

nombres_peliculas = list(peliculas.keys())
n = len(nombres_peliculas)
similar = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        similar[i,j] = similitud_coseno(matriz_peliculas[i],matriz_peliculas[j])
for i in range(n):
    orden = np.argsort(similar[i])
    parecida = orden[1]
    print("Las mas parecidas:\n", nombres_peliculas[i],"parecida",nombres_peliculas[parecida])

Las mas parecidas:
 Toy Story parecida Jumanji
Las mas parecidas:
 Jumanji parecida Toy Story
Las mas parecidas:
 Mortal Kombat parecida Toy Story
Las mas parecidas:
 Pocahontas parecida Mortal Kombat
